cp ./28_buggy_simple_loop1_vf_false-unreach-call_anno.c ./inv/
cp ./fib_bench_false-unreach-call_anno.c ./inv/
cp ./fib_bench_longer_false-unreach-call_anno.c ./inv/
cp ./fib_bench_longest_false-unreach-call_anno.c ./inv/
cp ./fkp2013_false-unreach-call_anno.c ./inv/
cp ./fkp2013_variant_false-unreach-call_anno.c ./inv/
cp ./queue_false-unreach-call_anno.c ./inv/
cp ./queue_longer_false-unreach-call_anno.c ./inv/
cp ./queue_longest_false-unreach-call_anno.c ./inv/
cp ./reorder_2_false-unreach-call_anno.c ./inv/
cp ./reorder_5_false-unreach-call_anno.c ./inv/
cp ./sigma_false-unreach-call_anno.c ./inv/
cp ./stack_false-unreach-call_anno.c ./inv/
cp ./stack_longer_false-unreach-call_anno.c ./inv/
cp ./stack_longest_false-unreach-call_anno.c ./inv/
cp ./twostage_3_false-unreach-call_anno.c ./inv/
