cp ./pagai/28_buggy_simple_loop1_vf_false-unreach-call.c ./cseq/
cp ./pagai/fib_bench_false-unreach-call.c ./cseq/
cp ./pagai/fib_bench_longer_false-unreach-call.c ./cseq/
cp ./pagai/fib_bench_longest_false-unreach-call.c ./cseq/
cp ./pagai/fkp2013_false-unreach-call.c ./cseq/
cp ./pagai/fkp2013_variant_false-unreach-call.c ./cseq/
cp ./pagai/queue_false-unreach-call.c ./cseq/
cp ./pagai/queue_longer_false-unreach-call.c ./cseq/
cp ./pagai/queue_longest_false-unreach-call.c ./cseq/
cp ./pagai/reorder_2_false-unreach-call.c ./cseq/
cp ./pagai/reorder_5_false-unreach-call.c ./cseq/
cp ./pagai/sigma_false-unreach-call.c ./cseq/
cp ./pagai/stack_false-unreach-call.c ./cseq/
cp ./pagai/stack_longer_false-unreach-call.c ./cseq/
cp ./pagai/stack_longest_false-unreach-call.c ./cseq/
cp ./pagai/twostage_3_false-unreach-call.c ./cseq/
